##### 1.  Create and Manipulate Arrays

Write a program to:

Create a NumPy array from a list
Reshape it into a 2×3 matrix
Print its shape and dimensions

In [7]:
import numpy as np

my_list=[1,2,3,4,5,6]
arr = np.array(my_list)

reshaped_arr = arr.reshape(2,3)

print("Reshaped Array: ",reshaped_arr)
print("Array shape: ",reshaped_arr.shape)
print("Dimensions:", reshaped_arr.ndim)

Reshaped Array:  [[1 2 3]
 [4 5 6]]
Array shape:  (2, 3)
Dimensions: 2


##### 2.  Indexing and Slicing

Given a 2D NumPy array, write code to:

Extract the second row
Extract the last column
Extract a submatrix

In [8]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

second_row = arr[1]
last_column = arr[:, -1]
submatrix = arr[0:2, 0:2]  #Extarct first 2 rows and first two columns

print("Original Array:\n", arr)
print("Second Row:", second_row)
print("Last Column:", last_column)
print("Submatrix:\n", submatrix)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second Row: [4 5 6]
Last Column: [3 6 9]
Submatrix:
 [[1 2]
 [4 5]]


##### 3.  Element-wise Operations

Write a program to:

Add, subtract, and multiply two NumPy arrays
Perform element-wise operations without using loops

In [9]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2

print("Array 1:", arr1)
print("Array 2:", arr2)

print("\nAddition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)

Array 1: [1 2 3]
Array 2: [4 5 6]

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]


##### 4. Statistical Operations

Given a NumPy array, write code to find:

Mean
Median
Standard deviation

In [10]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

mean_value = np.mean(arr)
median_value = np.median(arr)
std_deviation = np.std(arr)

print("Array:", arr)
print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_deviation)

Array: [10 20 30 40 50]
Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951


##### 5. Boolean Masking / Filtering

Write a program to:

Extract all elements greater than a given value (e.g., 50)
Replace all negative values with 0

In [11]:
import numpy as np

arr = np.array([10, 55, -3, 70, 25, -8, 90])

greater_than_50 = arr[arr > 50]

arr[arr < 0] = 0

print("Original Array after modification:", arr)
print("Elements greater than 50:", greater_than_50)

Original Array after modification: [10 55  0 70 25  0 90]
Elements greater than 50: [55 70 90]
